"""
Configuration module for E-Commerce Crawler.

This module provides centralized configuration management.
For backward compatibility, you can import settings directly:
    from config import settings
    # or
    from config.settings import *
"""

# Import all settings for backward compatibility
from config.settings import *

# Also export obfuscation utilities
from config.obfuscation import _decode_string, _obfuscate_string

__all__ = [
    # Settings
    'AWS_REGION',
    'DYNAMODB_TABLE',
    'COGNITO_USER_POOL_ID',
    'COGNITO_CLIENT_ID',
    'COGNITO_REGION',
    'COGNITO_IDENTITY_POOL_ID',
    'KEYRING_SERVICE_NAME',
    'SESSION_VALIDATION_INTERVAL_MS',
    'IMAGE_STORE_DIR',
    'MAX_PRODUCTS_TO_SCRAPE',
    'MODE',
    'API_GATEWAY_URL',
    'API_GATEWAY_HEADERS',
    # CSS Selectors
    'SEARCH_ITEM_SELECTOR',
    'PRODUCT_TITLE_SELECTOR',
    'PRODUCT_PRICE_CURRENT_SELECTOR',
    'PRODUCT_PRICE_ORIGINAL_SELECTOR',
    'PRODUCT_GALLERY_SELECTOR',
    'PRODUCT_SKU_SELECTOR',
    'PRODUCT_DESCRIPTION_CONTAINER',
    'PRODUCT_DESCRIPTION_SHADOW_HOST',
    'PRODUCT_DESCRIPTION_RICHTEXT',
    'PRODUCT_SEO_DESCRIPTION',
    'PRODUCT_DESC_VIEW_MORE_BTN',
    'PRODUCT_SELLPOINTS_SELECTOR',
    # Amazon selectors
    'AMAZON_SEARCH_ITEM_SELECTOR',
    'AMAZON_SEARCH_ITEM_FALLBACK',
    'AMAZON_SEARCH_ITEM_CONTAINER',
    'AMAZON_PRODUCT_TITLE_SELECTOR',
    'AMAZON_PRODUCT_PRICE_SELECTOR',
    'AMAZON_PRODUCT_PRICE_WHOLE',
    'AMAZON_PRODUCT_PRICE_FRACTION',
    'AMAZON_PRODUCT_LIST_PRICE',
    'AMAZON_PRODUCT_GALLERY_SELECTOR',
    'AMAZON_PRODUCT_MAIN_IMAGE',
    'AMAZON_PRODUCT_THUMBNAIL_SELECTOR',
    'AMAZON_PRODUCT_VARIANT_CONTAINER',
    'AMAZON_PRODUCT_VARIANT_ITEMS',
    'AMAZON_PRODUCT_VARIANT_IMAGES',
    'AMAZON_PRODUCT_VARIANT_BUTTONS',
    'AMAZON_PRODUCT_VARIANT_DROPDOWN',
    'AMAZON_PRODUCT_FEATURE_BULLETS',
    'AMAZON_PRODUCT_DESCRIPTION',
    'AMAZON_PRODUCT_DESCRIPTION_TEXT',
    'AMAZON_PRODUCT_APluS_CONTENT',
    'AMAZON_PRODUCT_ASIN_SELECTOR',
    'AMAZON_PRODUCT_BRAND_SELECTOR',
    'AMAZON_PRODUCT_RATING_SELECTOR',
    'AMAZON_PRODUCT_REVIEW_COUNT',
    'AMAZON_PRODUCT_TECH_DETAILS',
    'AMAZON_PRODUCT_INFO_TABLE',
    'AMAZON_SKU_SEE_MORE_LINK',
    'AMAZON_SKIP_IMAGE_PATTERNS',
    # Other settings
    'ENABLE_AMAZON_PRICE_SEARCH',
    'AMAZON_PRICE_SEARCH_MAX_RESULTS',
    'PRICE_DISCOUNT',
    'WAIT_PAGE_LOAD',
    'WAIT_SCROLL',
    'WAIT_ELEMENT_LOAD',
    'WAIT_BETWEEN_ACTIONS',
    'WAIT_BETWEEN_PRODUCTS',
    'ELEMENT_WAIT_TIMEOUT',
    # Utilities
    '_decode_string',
    '_obfuscate_string',
]

